"""
Tests for the Dragy VBO source adapter (U2).

Covers all plan test scenarios:
- detect_source returns 'dragy' for VBO columns; no misclassification
- _read_vbo yields correct row count and numeric values
- Each mapped column resolves to its expected canonical name
- Unmapped GPS/motion columns are explicitly None (skipped)
- Malformed short trailing rows are skipped, prior rows preserved
- Full ingest_file on sample fixture produces source:dragy with expected PIDs
"""

import json
import os
import sys
import tempfile
import textwrap

import pytest

# Allow running from repo root: python -m pytest tools/test_dragy_ingest.py
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from tools.schema import detect_source, SOURCE_COLUMN_MAP
from tools.mcp_server import _read_vbo, _is_vbo_file, ingest_file

SAMPLE_VBO = os.path.join(
    os.path.dirname(__file__), "..",
    "data", "sample",
    "dragylap_20260606_162501_HF Perris to Home.vbo",
)
SAMPLE_VBO = os.path.normpath(SAMPLE_VBO)

# ---------------------------------------------------------------------------
# Minimal VBO fixture for unit tests (avoids 14k-row sample in fast tests)
# ---------------------------------------------------------------------------

MINIMAL_VBO = textwrap.dedent("""\
    File created on 01/01/2026 @ 10:00

    [header]
    satellites
    time
    latitude
    longitude
    velocity kmh
    heading
    height
    rpm-obd
    speed-obd
    coolant_temp-obd
    intake_temp-obd
    manifold_flow-obd
    throttle_pos-obd
    engine_load-obd
    timing_advance-obd

    [channel units]

    [comments]
    Generated by dragy Lap

    [column names]
    sats time lat long velocity heading height rpm-obd speed-obd coolant_temp-obd intake_temp-obd manifold_flow-obd throttle_pos-obd engine_load-obd timing_advance-obd

    [data]
    010 100000.100 +2029.000000 +7033.000000 000.000 000.00 +00430.00 01200 +050.000 +090.000 +025.000 010.00 +020.000 +045.000
    010 100000.200 +2029.000000 +7033.000000 000.100 000.00 +00430.00 01500 +055.000 +090.000 +025.000 012.00 +025.000 +046.000
    010 100000.300 +2029.000000 +7033.000000 000.200 000.00 +00430.00 02000 +060.000 +091.000 +025.000 015.00 +030.000 +047.000
""")

MINIMAL_VBO_COLS = [
    "sats", "time", "lat", "long", "velocity", "heading", "height",
    "rpm-obd", "speed-obd", "coolant_temp-obd", "intake_temp-obd",
    "manifold_flow-obd", "throttle_pos-obd", "engine_load-obd", "timing_advance-obd",
]


@pytest.fixture
def minimal_vbo_file(tmp_path):
    p = tmp_path / "test_minimal.vbo"
    p.write_text(MINIMAL_VBO, encoding="utf-8")
    return str(p)


# ---------------------------------------------------------------------------
# detect_source tests
# ---------------------------------------------------------------------------

class TestDetectSource:
    def test_detects_dragy_from_obd_suffix_columns(self):
        assert detect_source(MINIMAL_VBO_COLS) == "dragy"

    def test_detects_dragy_with_only_one_obd_column(self):
        assert detect_source(["sats", "time", "rpm-obd"]) == "dragy"

    def test_dragy_not_misclassified_as_mhd(self):
        # MHD has (*F), WGDC, STFT 1 — dragy has none of those
        assert detect_source(MINIMAL_VBO_COLS) != "mhd"

    def test_dragy_not_misclassified_as_car_scanner(self):
        assert detect_source(MINIMAL_VBO_COLS) != "car_scanner"

    def test_dragy_not_misclassified_as_carobd(self):
        assert detect_source(MINIMAL_VBO_COLS) != "carobd"

    def test_dragy_not_misclassified_as_cephasax(self):
        assert detect_source(MINIMAL_VBO_COLS) != "cephasax"

    def test_dragy_not_misclassified_as_isay_gerard(self):
        assert detect_source(MINIMAL_VBO_COLS) != "isay_gerard"

    def test_mhd_not_misclassified_as_dragy(self):
        mhd_cols = ["RPM", "Boost (PSI)", "STFT 1 (%)", "Coolant (*F)"]
        assert detect_source(mhd_cols) == "mhd"

    def test_car_scanner_not_misclassified_as_dragy(self):
        cs_cols = ["Engine RPM (rpm)", "Engine coolant temperature (℉)"]
        assert detect_source(cs_cols) == "car_scanner"


# ---------------------------------------------------------------------------
# _is_vbo_file tests
# ---------------------------------------------------------------------------

class TestIsVboFile:
    def test_recognizes_vbo_file(self, minimal_vbo_file):
        assert _is_vbo_file(minimal_vbo_file) is True

    def test_rejects_csv_file(self, tmp_path):
        p = tmp_path / "test.csv"
        p.write_text("RPM,Boost (PSI)\n1200,5.0\n")
        assert _is_vbo_file(str(p)) is False

    def test_missing_file_returns_false(self):
        assert _is_vbo_file("/nonexistent/file.vbo") is False


# ---------------------------------------------------------------------------
# _read_vbo parsing tests
# ---------------------------------------------------------------------------

class TestReadVbo:
    def test_returns_correct_column_names(self, minimal_vbo_file):
        cols, rows = _read_vbo(minimal_vbo_file)
        assert cols == MINIMAL_VBO_COLS

    def test_returns_correct_row_count(self, minimal_vbo_file):
        cols, rows = _read_vbo(minimal_vbo_file)
        assert len(rows) == 3

    def test_rpm_values_are_numeric_strings(self, minimal_vbo_file):
        cols, rows = _read_vbo(minimal_vbo_file)
        rpm_vals = [float(r["rpm-obd"]) for r in rows]
        assert rpm_vals == [1200.0, 1500.0, 2000.0]

    def test_timing_advance_absent_when_data_field_missing(self, minimal_vbo_file):
        # timing_advance-obd is the last declared column but data rows have one
        # fewer field — it is naturally absent from parsed rows (zip stops early).
        cols, rows = _read_vbo(minimal_vbo_file)
        assert "timing_advance-obd" not in rows[0]

    def test_malformed_short_trailing_row_is_skipped(self, tmp_path):
        # A row with far too few fields (< half expected) should be skipped
        vbo = MINIMAL_VBO + "010\n"  # single field, clearly malformed
        p = tmp_path / "short_row.vbo"
        p.write_text(vbo, encoding="utf-8")
        cols, rows = _read_vbo(str(p))
        # Short row skipped — 3 good rows remain
        assert len(rows) == 3

    def test_empty_data_section_returns_no_rows(self, tmp_path):
        vbo = textwrap.dedent("""\
            [header]
            rpm-obd

            [column names]
            rpm-obd

            [data]
        """)
        p = tmp_path / "empty_data.vbo"
        p.write_text(vbo, encoding="utf-8")
        cols, rows = _read_vbo(str(p))
        assert rows == []


# ---------------------------------------------------------------------------
# SOURCE_COLUMN_MAP coverage tests
# ---------------------------------------------------------------------------

class TestSourceColumnMap:
    def test_obd_columns_map_to_canonical_names(self):
        expected = {
            "rpm-obd":           "RPM",
            "speed-obd":         "VSS",
            "coolant_temp-obd":  "ECT",
            "intake_temp-obd":   "IAT",
            "manifold_flow-obd": "MAF",
            "throttle_pos-obd":  "THROTTLE",
            "engine_load-obd":   "LOAD",
            "timing_advance-obd":"TIMING_ADV",
        }
        for raw_col, expected_canon in expected.items():
            result = SOURCE_COLUMN_MAP.get(("dragy", raw_col))
            assert result == expected_canon, f"({raw_col!r} → {result!r}, expected {expected_canon!r})"

    def test_gps_motion_columns_are_explicitly_none(self):
        skip_cols = ["sats", "time", "lat", "long", "velocity", "heading", "height", "acceleration-obd"]
        for col in skip_cols:
            result = SOURCE_COLUMN_MAP.get(("dragy", col), "NOT_IN_MAP")
            assert result is None, f"{col!r} should be None (explicit skip), got {result!r}"

    def test_obd_columns_not_silently_absent_from_map(self):
        obd_cols = [
            "rpm-obd", "speed-obd", "coolant_temp-obd", "intake_temp-obd",
            "manifold_flow-obd", "throttle_pos-obd", "engine_load-obd", "timing_advance-obd",
        ]
        for col in obd_cols:
            assert ("dragy", col) in SOURCE_COLUMN_MAP, f"Missing dragy mapping for {col!r}"


# ---------------------------------------------------------------------------
# Full ingest_file integration test
# ---------------------------------------------------------------------------

class TestIngestFileSample:
    """Uses the real 14,952-row sample fixture."""

    @pytest.fixture(autouse=True)
    def skip_if_missing(self):
        if not os.path.exists(SAMPLE_VBO):
            pytest.skip(f"Sample fixture not found: {SAMPLE_VBO}")

    def test_source_is_dragy(self):
        result = json.loads(ingest_file(SAMPLE_VBO))
        assert result.get("source") == "dragy"

    def test_row_count_default_cap(self):
        result = json.loads(ingest_file(SAMPLE_VBO))
        # Default max_rows=500 caps the reported row_count
        assert result["row_count"] == 500

    def test_all_obd_pids_present(self):
        result = json.loads(ingest_file(SAMPLE_VBO))
        pids = result.get("pids", {})
        # TIMING_ADV is declared in [column names] but absent from this capture's
        # data rows (column 15, data only has 15 fields 0-14). The other 7 must be present.
        expected_pids = {"RPM", "VSS", "ECT", "IAT", "MAF", "THROTTLE", "LOAD"}
        missing = expected_pids - set(pids.keys())
        assert not missing, f"Missing PIDs: {missing}"

    def test_no_gps_motion_pids_in_output(self):
        result = json.loads(ingest_file(SAMPLE_VBO))
        pids = result.get("pids", {})
        gps_names = {"sats", "time", "lat", "long", "velocity", "heading", "height", "acceleration-obd"}
        leaked = gps_names & set(pids.keys())
        assert not leaked, f"GPS/motion cols leaked into pids: {leaked}"

    def test_no_recognizable_obd2_columns_error_absent(self):
        result = json.loads(ingest_file(SAMPLE_VBO))
        assert "error" not in result

    def test_rpm_values_in_plausible_range(self):
        result = json.loads(ingest_file(SAMPLE_VBO, max_rows=15000))
        rpm = result["pids"]["RPM"]
        assert 500 <= rpm["mean"] <= 8000

    def test_coolant_temp_in_plausible_range(self):
        # Dragy reports coolant in °C already — no conversion needed
        result = json.loads(ingest_file(SAMPLE_VBO, max_rows=15000))
        ect = result["pids"]["ECT"]
        assert 60 <= ect["mean"] <= 120

    def test_full_sample_row_count_with_high_max(self):
        result = json.loads(ingest_file(SAMPLE_VBO, max_rows=20000))
        # 14,952 good rows in sample
        assert result["row_count"] == 14952


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
